global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: [ 'mosu-server:20000' ]

  - job_name: 'mysql'
    static_configs:
      - targets: [ 'mosu-mysql-exporter:9104' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ "mosu-redis-exporter:9121" ]

  - job_name: 'prometheus-self'
    static_configs:
      - targets: [ 'mosu-prometheus:9090' ]