global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mosu-server:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mosu-database:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ["mosu-redis-exporter:9121"]

  - job_name: 'prometheus-self'
    static_configs:
      - targets: ['mosu-prometheus:9090']