#server:
#  port: ${SPRING_PORT}
#  servlet:
#    context-path: ${BASE_PATH}
#    session:
#      cookie:
#        same-site: none
#        secure: false
#  error:
#    include-stacktrace: never
#
#spring:
#  config:
#    import:
#      - optional:file:.env[.properties]
#      - security-config.yml
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: ${MAX_FILE_SIZE}
#      max-request-size: ${MAX_REQUEST_SIZE}
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: true
#        jdbc:
#          time_zone: Asia/Seoul
#        dialect: org.hibernate.dialect.MySQLDialect
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_EXPORTER}
#      password: ${REDIS_PASSWORD}
#
#springdoc:
#  swagger-ui:
#    path: /swagger
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#aws:
#  s3:
#    bucket-name: ${AWS_BUCKET_NAME}
#    region: ${AWS_REGION}
#    access-key: ${AWS_ACCESS_KEY}
#    secret-key: ${AWS_SECRET_KEY}
#    presigned-url-expiration-minutes: ${S3_PRESIGNED_URL_EXPIRATION_MINUTES}
#
#logging:
#  file:
#    path: ./logs
#    name: app.log


server:
  port: ${SPRING_PORT}
  servlet:
    context-path: ${BASE_PATH}
    session:
      cookie:
        same-site: none
        secure: false
  error:
    include-stacktrace: never

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - security-config.yml
      - swagger-config.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_EXPORTER}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    presigned-url-expiration-minutes: ${S3_PRESIGNED_URL_EXPIRATION_MINUTES}

logging:
  file:
    path: ./logs
    name: app.log