name: Just Build with JDK 21

on:
  pull_request:
    branches:
      - 'develop'

  push:
    branches:
      - 'develop'
      - 'fix/**'
      - 'feature/**'

  workflow_dispatch:

jobs:
  build_and_ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Test And Build with Gradle
        run: ./gradlew clean build
